config/routes.rb
Rails.application.routes.draw do
root "homes#top"
get "about" => "homes#about"
post "follow/:id" => "relationships#follow", as: "follow"
post "unfollow/:id" => "relationships#unfollow", as: "unfollow"
post "users/guest_sign_in" => "users#new_guest"
devise_for :users
resources :shops, only: [:index, :new, :create, :show] do
  resource :shop_recommendations, only: [:create, :destroy, :index]
end
resources :posts do
  resource :favorites, only: [:create, :destroy]
  resources :post_comments, only: [:create, :destroy]
end
resources :users
resources :areas, only: [:show]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if post.favorited_by?(current_user) %>
    <li>
      <%= link_to post_favorites_path(post),method: :delete, remote: true do %>
        <i class="fas fa-heart heart_favorited"></i>お気に入り(<%= post.favorites.count %>)
      <% end %>
    </li>
  <% else %>
    <li>
      <%= link_to post_favorites_path(post),method: :post, remote: true do %>
        お気に入り(<%= post.favorites.count %>)
      <% end %>
    </li>
  <% end %>
<% end %>

app/views/favorites/_index.html.erb
<div class= "favorites_index_content">
  <h1>favorite</h1>
  <% if favorites.blank? %>
    <h6>まだお気に入りが登録されていません</h6>
  <% else %>
    <div class= "favorites_index">
      <% favorites.each do |favorite| %>
        <div class= "favorite_item post_item">
          <%= link_to post_path(favorite.post) do %>
            <%= attachment_image_tag favorite.post, :image, size: "300x300", format: "jpeg", class: "mt-2 rounded" %>
          <% end %>
          <p><%= favorite.post.area.area_name %> 　<%= favorite.post.shop.name.truncate(15) %></p>
        </div>
      <% end %>
      <%= paginate favorites, param_name: "favorites_pagina", class: "paginate", remote: true %>
    </div>
  <% end %>
</div>

app/views/favorites/create.js.erb
$('#favorites_button').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_button').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");