config/routes.rb
Rails.application.routes.draw do
root "homes#top"
get "about" => "homes#about"
post "follow/:id" => "relationships#follow", as: "follow"
post "unfollow/:id" => "relationships#unfollow", as: "unfollow"
post "users/guest_sign_in" => "users#new_guest"
devise_for :users
resources :shops, only: [:index, :new, :create, :show] do
  resource :shop_recommendations, only: [:create, :destroy, :index]
end
resources :posts do
  resource :favorites, only: [:create, :destroy]
  resources :post_comments, only: [:create, :destroy]
end
resources :users
resources :areas, only: [:show]
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :posts
  has_many :shop_recommendations, dependent: :destroy
  belongs_to :user, optional: true
  belongs_to :area
  validates :name, presence: true
  validates :address, presence: true
  validates :area_id, presence: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.search(search_area,search_shop)
    search_area_name= Area.find_by(area_name: search_area)
    search_shop_name= Shop.where("shops.name LIKE ?", "%#{search_shop}%")

    if search_area_name.blank? and search_shop_name.blank?
      Shop.all
    elsif search_area_name.blank?
      search_shop_name
    elsif search_shop_name.blank?
      search_area_id = search_area_name.id
      Shop.where(area_id: search_area_id)
    else
      search_area_id = search_area_name.id
      Shop.where(area_id: search_area_id).where("shops.name LIKE ?", "%#{search_shop}%")
    end
  end

  def shop_recommended_by?(user)
    shop_recommendations.where(user_id: user.id).exists?
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @shops = Shop.search(params[:search_area],params[:search_shop]).page(params[:page]).reverse_order
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to shop_path(@shop)
    else
      render "shops/new"
    end
  end

  def show
    @shop = Shop.find(params[:id])
    @shop_posts = @shop.posts.page(params[:posts_pagina]).order(created_at: :desc)
  end

  private

  def shop_params
    params.require(:shop).permit(:name,:area_id,:address,:order_postal_code,
      :phone_number,:open_time,:close_time,:min_average_price,:max_average_price)
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_shop_form.html.erb
<div class= "shop_info_form">
  <% if @shop.errors.any? %>
    <div class= "error_explanation">
      <p><%= @shop.errors.count %>件の入力の誤りがあります</p>
      <div class= "error_messages">
        <% @shop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= form_for(@shop) do |f| %>
    <table class= "table table-bordered bg-white">
      <tr>
        <th>名前</th>
        <td><%= f.text_field :name, placeholder: "店舗名", class: "shop_name_form" %></td>
      </tr>
      <tr>
        <th>地域</th>
        <td><%= f.select :area_id, Area.all.map{|o| [o.area_name, o.id]} %></td>
      </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= f.text_field :order_postal_code, placeholder: "郵便番号" %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= f.text_field :address, placeholder: "住所", class: "shop_address_form" %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= f.text_field :phone_number, placeholder: "電話番号", class: "shop_phone_number_form" %></td>
      </tr>
      <tr>
        <th>営業時間</th>
        <td>
          <%= f.time_field :open_time, placeholder: "営業開始時間" %>
          ~
          <%= f.time_field :close_time, placeholder: "営業終了時間" %>
        </td>
      </tr>
      <tr>
        <th>平均予算</th>
        <td>
          <%= f.number_field :min_average_price, min:1 %>
          ~
          <%= f.number_field :max_average_price, min:1 %>
        </td>
      </tr>
    </table>
    <%= f.submit "登録する", class: "shop_form_submit btn-secondary" %>
  <% end %>
</div>

app/views/shops/_show.html.erb
<div class= "contents shop_show_content">
  <h1>店舗情報</h1>
  <div class= "shop_show_top_items">
    <% if user_signed_in? %>
      <%= link_to "このお店について投稿する", new_post_path(:shop_id => shop.id, :area_id => shop.area_id), class: "shop_show_post_new_link" %>
      <div id= "shop_recommend_button">
        <%= render "shop_recommendations/shop_recommendation", shop: shop %>
      </div>
    <% end %>
  </div>
  <table class= "table table-bordered bg-white">
    <tr>
      <th>店舗名</th>
      <td><%= link_to shop.name, shop_path(shop) %></td>
    </tr>
    <tr>
      <th>地域</th>
      <td><%= link_to shop.area.area_name, area_path(shop.area) %></td>
    </tr>
     <tr>
      <th>郵便番号</th>
      <td><%= shop.order_postal_code %></td>
    </tr>
     <tr>
      <th>住所</th>
      <td>
        <%= shop.address %>
        <script type="text/javascript">
          function initMap() {

            var map_address ={lat: <%= shop.latitude %>, lng: <%= shop.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 15,
                center: map_address
            });
            var transitLayer = new google.maps.TransitLayer();
            transitLayer.setMap(map);

            var contentString = '住所：<%= shop.address %>';
            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });

            var marker = new google.maps.Marker({
                position:map_address,
                map: map,
                title: contentString
            });

            marker.addListener('click', function() {
                infowindow.open(map, marker);
            });
          }
        </script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
        </script>
        <div id="map"></div>
      </td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= shop.phone_number %></td>
    </tr>
    <tr>
      <th>営業時間</th>
      <td>
        <%= shop.open_time %>
        ~
        <%= shop.close_time %>
      </td>
    </tr>
    <tr>
      <th>平均予算</th>
      <td>
        <%= shop.min_average_price %>
        ~
        <%= shop.max_average_price %>円
      </td>
    </tr>
  </table>
</div>

app/views/shops/index.html.erb
<div class= "container contents shop_index_content">
  <h1>検索されたお店</h1>
  <table class= "table table-bordered bg-white">
    <tr>
      <th>地域</th>
      <th>店舗名</th>
    </tr>
    <% @shops.each do |shop| %>
      <tr>
      <td><%= link_to shop.area.area_name, area_path(shop.area) %></td>
      <td><%= link_to shop.name, shop_path(shop) %></td>
      </tr>
    <% end %>
  </table>
  <%= paginate @shops, class: "paginate" %>
  <p>↓まだお店の情報が登録されていない場合はこちらから</p>
  <%= link_to "新しくお店を登録する", new_shop_path %>
</div>

app/views/shops/new.html.erb
<div class= "container contents shop_new_content">
  <h1>お店を登録</h1>
  <%= render "shops/shop_form", shop: @shop %>
</div>

app/views/shops/show.html.erb
<div class= "container">
 <%= render "shops/show", shop: @shop %>
 <div class= "shop_show_posts_section">
  <% unless @shop_posts.count < 1 %>
    <h1>snap shots<br>- <%= @shop.name %> -</h1>
    <%= render "posts/index", posts: @shop_posts %>
  <% end %>
 </div>
</div>