config/routes.rb
Rails.application.routes.draw do
root "homes#top"
get "about" => "homes#about"
post "follow/:id" => "relationships#follow", as: "follow"
post "unfollow/:id" => "relationships#unfollow", as: "unfollow"
post "users/guest_sign_in" => "users#new_guest"
devise_for :users
resources :shops, only: [:index, :new, :create, :show] do
  resource :shop_recommendations, only: [:create, :destroy, :index]
end
resources :posts do
  resource :favorites, only: [:create, :destroy]
  resources :post_comments, only: [:create, :destroy]
end
resources :users
resources :areas, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :shops
  has_many :posts
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  belongs_to :user, optional: true
  belongs_to :shop, optional: true
  belongs_to :area, optional: true
  attachment :image
  validates :comment, presence: true, length: {maximum: 200}
  validates :image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true, length: {maximum: 100}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :posts
  has_many :shop_recommendations, dependent: :destroy
  belongs_to :user, optional: true
  belongs_to :area
  validates :name, presence: true
  validates :address, presence: true
  validates :area_id, presence: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.search(search_area,search_shop)
    search_area_name= Area.find_by(area_name: search_area)
    search_shop_name= Shop.where("shops.name LIKE ?", "%#{search_shop}%")

    if search_area_name.blank? and search_shop_name.blank?
      Shop.all
    elsif search_area_name.blank?
      search_shop_name
    elsif search_shop_name.blank?
      search_area_id = search_area_name.id
      Shop.where(area_id: search_area_id)
    else
      search_area_id = search_area_name.id
      Shop.where(area_id: search_area_id).where("shops.name LIKE ?", "%#{search_shop}%")
    end
  end

  def shop_recommended_by?(user)
    shop_recommendations.where(user_id: user.id).exists?
  end

end

app/models/shop_recommendation.rb
class ShopRecommendation < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :shop_recommendations, dependent: :destroy
  has_many :shops
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :post_comments, dependent: :destroy
  attachment :user_image
  validates :name, presence: true, length: {maximum: 10}
  validates :introduction, length: {maximum: 200}
  validates :email, length: {minimum: 5, maximum: 70}

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def search_follower_user(user)
    user.follower_user.where.not(id: user.id)
  end

  def search_following_user(user)
    user.following_user.where.not(id: user.id)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end

  def shop_recommendations_count_over?(user)
    user.shop_recommendations.count > 4
  end

  def user_post_areas_count
    self.posts.joins(:area).group("areas.area_name").count
  end

end

app/models/user_favorite.rb
class UserFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

  def show
    @area = Area.find(params[:id])
    @area_posts = @area.posts.page(params[:posts_pagina]).order(created_at: :desc)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    if user_signed_in?
      @posts = current_user.feed.page(params[:posts_pagina]).order(created_at: :desc)
      @users = User.where.not(id: current_user.id).page(params[:users_pagina]).reverse_order
    else
      @posts = Post.page(params[:posts_pagina]).order(created_at: :desc)
      @users = User.page(params[:users_pagina]).reverse_order
    end
      @areas = Area.all
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    posts = Post.page(params[:page]).order(created_at: :desc)
  end

  def new
    @post = Post.new
    @post.shop_id = params[:shop_id]
    @post.area_id = params[:area_id]
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      render "posts/new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render "posts/edit"
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_page_comments = @post.post_comments.page(params[:post_comments_pagina]).reverse_order
    @post_comment = PostComment.new
    @user = @post.user
    @following_users = @user.search_following_user(@user).page(params[:following_pagina]).reverse_order
    @follower_users = @user.search_follower_user(@user).page(params[:follower_pagina]).reverse_order
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:comment, :image, :rating, :shop_id, :area_id)
  end

  def ensure_correct_user
    post = Post.find(params[:id])
    if post.user_id != current_user.id
      redirect_to root_path
    end
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def follow
    @user = User.find(params[:id])
    current_user.follow(params[:id])
    @following_users = @user.search_following_user(@user).page(params[:page]).reverse_order
    @follower_users = @user.search_follower_user(@user).page(params[:page]).reverse_order
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow(params[:id])
    @following_users = @user.search_following_user(@user).page(params[:page]).reverse_order
    @follower_users = @user.search_follower_user(@user).page(params[:page]).reverse_order
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @shops = Shop.search(params[:search_area],params[:search_shop]).page(params[:page]).reverse_order
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to shop_path(@shop)
    else
      render "shops/new"
    end
  end

  def show
    @shop = Shop.find(params[:id])
    @shop_posts = @shop.posts.page(params[:posts_pagina]).order(created_at: :desc)
  end

  private

  def shop_params
    params.require(:shop).permit(:name,:area_id,:address,:order_postal_code,
      :phone_number,:open_time,:close_time,:min_average_price,:max_average_price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/relationships/_follow_link.html.erb
<% if user_signed_in? %>
  <% unless user == current_user %>
    <div id= "follow_link">
      <% if current_user.following?(user) %>
        <%= link_to "フォロー解除", unfollow_path(user.id), method: :post,class: "btn btn-danger", remote: true %>
      <% else %>
        <%= link_to "フォローする", follow_path(user.id), method: :post,class: "btn btn-primary", remote: true %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/relationships/_follow_people_num.html.erb
 <div class= "follow_count_items tab_menu">
   <a href= "#user_following"><%= "フォロー #{user.follower.count}" %></a>
   <a href= "#user_followed"><%= "フォロワー #{user.followed.count}" %></a>
</div>

app/views/relationships/_follower.html.erb
<div class = "follower_index follow_user_index_content">
  <h4>フォロワー</h4>
  <% if follower_users.count < 1 %>
    <p>フォロワーはいません</p>
  <% else %>
    <table class= "table table-dark table-striped follow_user_index_table">
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
      <% follower_users.each do |user| %>
        <tr class = "follower_user follow_people">
          <td>
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :user_image, size: "40x40", format: "jpeg", fallback: asset_path("default-icon-img.jpeg"), class: "rounded-circle" %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td><%= link_to "詳細", user_path(user) %></td>
        </tr>
      <% end %>
      <%= paginate follower_users, param_name: "follower_pagina", class: "paginate", remote: true %>
    </table>
  <% end %>
</div>

app/views/relationships/_following.html.erb
<div class = "following_index follow_user_index_content">
  <h4>フォロー中</h4>
  <% if following_users.count < 1 %>
    <p>フォロー中のユーザーはいません</p>
  <% else %>
    <table class= "table table-dark table-striped follow_user_index_table">
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
      <% following_users.each do |user| %>
        <tr class = "following_user follow_people">
          <td>
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :user_image, size: "40x40", format: "jpeg", fallback: asset_path("default-icon-img.jpeg"), class: "rounded-circle" %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td><%= link_to "詳細", user_path(user) %></td>
        </tr>
      <% end %>
      <%= paginate following_users, param_name: "following_pagina", class: "paginate", remote: true %>
    </table>
  <% end %>
</div>

app/views/relationships/follow.js.erb
$(".follow_button").html("<%= j(render 'relationships/follow_link', user: @user) %>");
$("#follow_counts").html("<%= j(render 'relationships/follow_people_num', user: @user) %>");
$("#user_followed").html("<%= j(render 'relationships/follower', follower_users: @follower_users) %>");

app/views/relationships/unfollow.js.erb
$(".follow_button").html("<%= j(render 'relationships/follow_link', user: @user) %>");
$("#follow_counts").html("<%= j(render 'relationships/follow_people_num', user: @user) %>");
$("#user_followed").html("<%= j(render 'relationships/follower', follower_users: @follower_users) %>");