config/routes.rb
Rails.application.routes.draw do
root "homes#top"
get "about" => "homes#about"
post "follow/:id" => "relationships#follow", as: "follow"
post "unfollow/:id" => "relationships#unfollow", as: "unfollow"
post "users/guest_sign_in" => "users#new_guest"
devise_for :users
resources :shops, only: [:index, :new, :create, :show] do
  resource :shop_recommendations, only: [:create, :destroy, :index]
end
resources :posts do
  resource :favorites, only: [:create, :destroy]
  resources :post_comments, only: [:create, :destroy]
end
resources :users
resources :areas, only: [:show]
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  belongs_to :user, optional: true
  belongs_to :shop, optional: true
  belongs_to :area, optional: true
  attachment :image
  validates :comment, presence: true, length: {maximum: 200}
  validates :image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    posts = Post.page(params[:page]).order(created_at: :desc)
  end

  def new
    @post = Post.new
    @post.shop_id = params[:shop_id]
    @post.area_id = params[:area_id]
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      render "posts/new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render "posts/edit"
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_page_comments = @post.post_comments.page(params[:post_comments_pagina]).reverse_order
    @post_comment = PostComment.new
    @user = @post.user
    @following_users = @user.search_following_user(@user).page(params[:following_pagina]).reverse_order
    @follower_users = @user.search_follower_user(@user).page(params[:follower_pagina]).reverse_order
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:comment, :image, :rating, :shop_id, :area_id)
  end

  def ensure_correct_user
    post = Post.find(params[:id])
    if post.user_id != current_user.id
      redirect_to root_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.erb
<div class= "post_index">
  <div class= "post_items">
    <% posts.each do |post| %>
      <div class= "post_item">
        <%= link_to post_path(post) do %>
          <%= attachment_image_tag post, :image, size: "300x300", format: "jpeg", class: "mt-2 rounded" %>
        <% end %>
        <p><%= post.area.area_name %>　　<%= post.shop.name.truncate(15) %></p>
      </div>
    <% end %>
    <%= paginate posts, param_name: "posts_pagina", class: "paginate", remote: true %>
  </div>
</div>

app/views/posts/_post_form.html.erb
<div class= "post_form_content">
  <% if post.errors.any? %>
    <div class= "error_explanation">
      <p><%= post.errors.count %>件の入力の誤りがあります</p>
      <div class= "error_messages">
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= form_with model: post, local: true do |f| %>
    <div class= "row post_form_section">
      <div class= "col-4 post_form_image_section">
        <div id= "post_image_preview">
          <% if post.image.present? %>
            <%= attachment_image_tag post, :image, size: "300x300", format: "jpeg", class: "rounded" %>
          <% end %>
        </div>
        <label>写真の選択(必須)</label>
        <%= f.attachment_field :image, direct: true %>
      </div>

      <div class= "col-8 post_text_form_section_items">
        <table class= "table table-bordered bg-light">
          <tr>
            <th>コメント</th>
            <td><%= f.text_area :comment, placeholder: "コメントを入力(200文字以内)",rows: "7" %></td>
          </tr>
          <tr>
            <th>評価</th>
            <td><%= f.select :rating,[1,2,3,4,5] %></td>
          </tr>
        </table>
        <%= f.hidden_field :shop_id, :value => @post.shop_id %>
        <%= f.hidden_field :area_id, :value => @post.area_id %>
        <%= f.submit "投稿する",class: "btn btn-info post_form_submit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class = "container contents post_edit_content">
  <h1>投稿編集</h1>
  <%= render "posts/post_form", post: @post %>
  <%= link_to "投稿を削除する", post_path(@post), method: :delete, "data-confirm" => "本当に削除してよろしいですか？",class: "btn btn-danger" %>
</div>

app/views/posts/new.html.erb
<div class= "container contents post_new_content">
  <h1>新規投稿</h1>
  <%= render "posts/post_form", post: @post %>
</div>

app/views/posts/show.html.erb
<div class= "container">
  <div class= "row post_show_top_contents">
    <div class= "col-10">
      <%= render "users/user_top_info", user: @user %>
    </div>
    <div class= "col-2 shop_recommendations_section">
      <%= render "shop_recommendations/index", shop_recommendations: @user.shop_recommendations %>
    </div>
  </div>

  <div class= "tab_menu_contents">
    <ul class= "tab_menu tab_menu_items">
      <li>|<a href= "#post_user_show" class= "a_active">投稿</a></li>
      <li>|<a href= "#post_shop_show">店舗情報</a>|</li>
      <li id= "post_comment_tab"><%= render "post_comments/post_comment_tab", post: @post %></li>
    </ul>
  </div>

  <div class= "tab_contents">
    <div id= "user_following" class= "tab tab1">
      <%= render "relationships/following", following_users: @following_users %>
    </div>

    <div id= "user_followed" class= "tab tab2">
      <%= render "relationships/follower", follower_users: @follower_users %>
    </div>

    <div id= "post_user_show" class= "row tab tab3">
      <div class= "col-5 post_show_image"><%= attachment_image_tag @post, :image, size: "300x300", format: "jpeg", class: "rounded" %></div>
      <div class= "col-7">
        <div class= "post_show_shop_name_section">
          <h3>店舗名</h3>
          <h4><%= link_to @post.shop.name, shop_path(@post.shop_id) %></h4>
        </div>
        <div class= "post_show_shop_review_section">
          <h5>レビュー</h5>
          <p><%= @post.comment %></p>
        </div>
        <div class= "post_show_shop_rating_section">
          <h5>評価</h5>
          <p><%= @post.rating %></p>
        </div>
        <div id= "favorites_button">
          <%= render "favorites/favorite", post: @post %>
        </div>
        <div class= "post_show_edit_section">
          <% if @post.user == current_user %>
            <p><%= link_to "投稿を編集する", edit_post_path(@post) %></p>
          <% end %>
        </div>
      </div>
    </div>

    <div id= "post_shop_show" class= "tab tab4">
      <%= render "shops/show", shop: @post.shop %>
    </div>

    <div id= "post_comments" class= "tab tab5">
      <%= render "post_comments/post_comment", post: @post, post_page_comments: @post_page_comments, post_comment: @post_comment %>
    </div>
  </div>
</div>

app/views/posts/show.js.erb
$("#user_following").html("<%= j(render 'relationships/following', following_users: @following_users) %>");
$("#user_followed").html("<%= j(render 'relationships/follower', follower_users: @follower_users) %>");
$("#post_comments").html("<%= j(render 'post_comments/post_comment',post: @post, post_page_comments: @post_page_comments, post_comment: @post_comment) %>");